[package]
name = "wolf3d"
version = "1.0.0"
edition = "2021"

[dependencies]
serde_json = "1.0.41"
good-web-game = "0.4.1"
miniquad = "=0.3.0-alpha.37"
cgmath = { version = "0.17", features = ["mint"] }

#[profile.release]
#lto = true
